title: "u-terminal"
tagline: "A jekyll theme that looks like a shell/terminal"
description: "u-terminal website"
github_username: s2quake
# baseurl: "/jekyll-shell-theme"
# url: "https://u-terminal.github.io"

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-youtube

sass:
  style: compressed

highlighter: rouge

header_pages:
  - index.md
  - media.md
  - about.md

# set the size of the text to 'large' or 'small', default is small
font-size: small
